Properly filter warnings from chmod

diff --git a/.github/workflows/format-check.yml b/.github/workflows/format-check.yml
--- a/.github/workflows/format-check.yml
+++ b/.github/workflows/format-check.yml
@@ -46,8 +46,8 @@ jobs:
     - name: Check code format
       run: Tools/run-swift-format.sh -d lint
 
-    - name: Fix permissions
+    - name: Fix permissions to keep cache happy.
       run: |
-        chmod -v -R +rX .build Package.resolved 2> /dev/null | while read -r line; do
-          echo "::warning title=Invalid file permissions automatically fixed::$line"
+        chmod -v -R +rX .build | (grep -v "mode of '.*' retained as " || true) | while read -r message; do
+          echo "::warning title=Invalid file permissions automatically fixed::$message"
         done
